require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'config/deploy/*'
    - 'config/deploy.rb'
    - 'config/unicorn.rb'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'test/test_helper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'app/api/client_api/*'
    - 'app/api/concerns/*'

Metrics/LineLength:
  Max: 120

Style/IfUnlessModifier:
  MaxLineLength: 120

Style/WhileUntilModifier:
  MaxLineLength: 120

Style/ClassAndModuleChildren:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: rails

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: true
  Max: 6

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Max: 7

RSpec/DescribeClass:
  Exclude:
    - "spec/features/**.rb"

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "lib/tasks/**/*.rake"
    - "spec/factories/**.rb"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*.rb"

Metrics/AbcSize:
  Exclude:
    - "db/migrate/*.rb"

